@startuml

!include C4_Component.puml

Container_Boundary(webapp, "Warmhouse Website") {
    Component(authComponent, "Login Component", "UI Component", $descr="Authenticates user and manages authentication state")
    Component(deviceComponent, "Device Manager", "UI Component", $descr="Allows to manage devices: add, remove, observe. Allows to send commands to devices")
    Component(videoComponent, "Video Component", "UI Component", $descr="Allows to watch life or recorded videos from cameras")
}

System_Ext(deviceMgr, "Device Management Service")
System_Ext(video, "Video Processing Service")
System_Ext(authService, "Authentication Service")

Rel(authComponent, authService, "Generating auth token")
Rel(deviceComponent, deviceMgr, "Manages all devices")
Rel(videoComponent, video, "Requests video")
@enduml
